CC = gcc
CFLAGS = -Wall -lm -Iraylib/include -Lraylib/lib -lraylib # for Linux
#CFLAGS = -Wall -Iraylib/include -Lraylib/lib -lraylib -framework Cocoa -framework IOKit -framework CoreVideo # for MacOS

main: main.c
	$(CC) $(CFLAGS) $< -o $@

