CC = gcc
# For Linux
CFLAGS = -Wall -lm -Iraylib/include -Lraylib/lib -lraylib
# For MacOS
#CFLAGS = -Wall -Iraylib/include -Lraylib/lib -lraylib -framework Cocoa -framework IOKit -framework CoreVideo

main: main.c
	$(CC) $(CFLAGS) $< -o $@

